apiVersion: v1
kind: Secret
metadata:
  name: harbor-registry
  namespace: banking # Đổi thành namespace ứng dụng của bạn
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: |
    {
      "auths": {
        "192.168.6.64": {
          "username": "admin",
          "password": "Group-hcm-01"
        }
      }
    }
