apiVersion: v1
kind: Secret
metadata:
  name: harbor-registry
  namespace: banking
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: eyJhdXRocyI6eyJoYXJib3IuY21jLWNsb3VkLWhjbTEuY2xvdWQiOnsidXNlcm5hbWUiOiJhZG1pbiIsInBhc3N3b3JkIjoiR3JvdXAtaGNtLTAxIiwiYXV0aCI6IllXUnRhVzQ2UjNKdmRYQXRhR050TFRBeCJ9fX0=
